ERROR - 2023-01-29 21:46:32 --> Unknown column 'email' in 'where clause'
CRITICAL - 2023-01-29 21:46:32 --> Unknown column 'email' in 'where clause'
#0 C:\xampp\htdocs\pkl\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\pkl\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\pkl\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\pkl\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pkl\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pkl\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 C:\xampp\htdocs\pkl\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 C:\xampp\htdocs\pkl\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\pkl\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-01-29 21:46:45 --> Unknown column 'email' in 'where clause'
CRITICAL - 2023-01-29 21:46:45 --> Unknown column 'email' in 'where clause'
#0 C:\xampp\htdocs\pkl\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\pkl\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\pkl\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\pkl\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pkl\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pkl\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 C:\xampp\htdocs\pkl\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 C:\xampp\htdocs\pkl\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\pkl\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-01-29 22:06:52 --> Unknown column 'email' in 'where clause'
CRITICAL - 2023-01-29 22:06:52 --> Unknown column 'email' in 'where clause'
#0 C:\xampp\htdocs\pkl\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\pkl\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\pkl\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\pkl\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pkl\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pkl\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 C:\xampp\htdocs\pkl\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 C:\xampp\htdocs\pkl\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\pkl\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-01-29 22:15:08 --> Unknown column 'email' in 'where clause'
CRITICAL - 2023-01-29 22:15:08 --> Unknown column 'email' in 'where clause'
#0 C:\xampp\htdocs\pkl\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\pkl\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\pkl\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\pkl\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\pkl\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\pkl\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 C:\xampp\htdocs\pkl\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 C:\xampp\htdocs\pkl\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\pkl\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-29 22:21:54 --> syntax error, unexpected single-quoted string "kepalakel", expecting "]"
#0 C:\xampp\htdocs\pkl\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('form2')
#1 C:\xampp\htdocs\pkl\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('form2')
#2 C:\xampp\htdocs\pkl\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\pkl\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-01-29 22:22:18 --> syntax error, unexpected single-quoted string "kepalakel", expecting "]"
#0 C:\xampp\htdocs\pkl\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('form2')
#1 C:\xampp\htdocs\pkl\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('form2')
#2 C:\xampp\htdocs\pkl\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\pkl\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-01-29 22:32:40 --> There is no data to insert.
#0 C:\xampp\htdocs\pkl\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\pkl\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 C:\xampp\htdocs\pkl\system\BaseModel.php(658): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#3 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#4 C:\xampp\htdocs\pkl\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#5 C:\xampp\htdocs\pkl\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 C:\xampp\htdocs\pkl\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-01-29 22:33:24 --> There is no data to insert.
#0 C:\xampp\htdocs\pkl\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\pkl\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 C:\xampp\htdocs\pkl\system\BaseModel.php(658): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#3 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#4 C:\xampp\htdocs\pkl\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#5 C:\xampp\htdocs\pkl\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 C:\xampp\htdocs\pkl\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-01-29 22:33:49 --> There is no data to insert.
#0 C:\xampp\htdocs\pkl\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\pkl\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 C:\xampp\htdocs\pkl\system\BaseModel.php(658): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#3 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#4 C:\xampp\htdocs\pkl\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#5 C:\xampp\htdocs\pkl\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 C:\xampp\htdocs\pkl\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-01-29 22:35:20 --> There is no data to insert.
#0 C:\xampp\htdocs\pkl\system\BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\pkl\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 C:\xampp\htdocs\pkl\system\BaseModel.php(658): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#3 C:\xampp\htdocs\pkl\vendor\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#4 C:\xampp\htdocs\pkl\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#5 C:\xampp\htdocs\pkl\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 C:\xampp\htdocs\pkl\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\pkl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
